### ISSUE TITLE
Can't decode cyrilic symbols

### ISSUE THREAD

**Issue by megamorphf** [podshumok/python-smpplib#23]
After attaching a handler on received sms. I parse out sms body from:

``` python
def on_receive(pdu):
    """This function is called when new sms is received"""
    source = pdu.source_addr

    message = pdu.short_message


    received = str(datetime.now().isoformat())
    logger.info('SOURCE:"{}" | MSG:"{}" '.format(source, message))

```

sms text = "ше_machines_ше"
printed sms output = ??_machines_??

The issue occurs when I parse out the data to a message variable. If I try printing that data I get question marks.  What should be done to get the correct symbols?

**Comment by podshumok** [comment]
set_message_received_handler in README is used for receiving delivery status information (DELIVER_SM)

if it is not what you facing, then may be you should do some decoding? Another possibility is that your SMSC doesn't support non-gsm encodings...

**Comment by megamorphf** [comment]
Yeah I've figured this out on my own. You may close this issue now, For those who need help with decoding here is an example code that will do the proper encoding based on smpp 3.4 documentation.

```python
def convert_to_unicode(pdu):
    coding = int(pdu.data_coding)
    message = pdu.short_message

    logger.debug("CODING VALUE: {}".format(coding))
    if coding == 0:
        ascii_message = message.decode('ascii').encode('utf8')
        logger.debug('Data coding is: "SMSC Default": {}'.format(ascii_message))
        return ascii_message
    elif coding == 3:
        latin_message = message.decode('latin-1').encode('utf8')
        logger.debug('Data coding is: "LATIN-1": {}'.format(latin_message))
        return latin_message
    elif coding == 8:
        unicode_message = message.decode('utf-16-be').encode('utf8')
        logger.debug('Data coding is: "UCS-2BE": {}'.format(unicode_message))
        return unicode_message
    else:
        raise ValueError('Undefined data coding in the pdu.data_coding field')

```

**Comment by podshumok** [comment]
You can actually propose a PR with that function

**Comment by fpalamour** [comment]
Hello guys,

I'm sorry to revive this but I'm struggling to decode UCS2 encoded short_message when users reply with unicode characters. My provider returns a data_coding with a value of 8 so it means I have to convert it to utf8 in order to correctly store it in my DB. The only issue is that, for me, pdu.short_message is a str type, which obviously doesn't have a decode() function, but only an encode() one. I tried messing with python encode / decode functions, trying many encodings possible like utf-16, utf-16-be, utf8 in every possible combination for two days now without achieving anything.

Would guys have any idea that could help me ?

**Comment by fpalamour** [comment]
I finally found the cause of my problem. I was already casting pdu.short_message to string when testing the deliver_sm pdu to figure out if it's a DLR or a MO. My bad.
