### ISSUE TITLE
Unkwown status

### ISSUE THREAD

**Issue by eabumere** [podshumok/python-smpplib#25]
Please help review this error

Traceback (most recent call last):
  File "C:\Python27\smpplib\another.py", line 42, in <module>
    client.listen()
  File "C:\Python27\smpplib\smpplib\client.py", line 285, in listen
    consts.DESCRIPTIONS.get(p.status, 'Unknown status')), int(p.status))
smpplib.exceptions.PDUError: ('(11) submit_sm_resp: Invalid Destination Address', 11)
DEBUG:smpplib.client:Sending unbind PDU
DEBUG:smpplib.client:>>00000010000000060000000000000002 (16 bytes)
DEBUG:smpplib.client:Waiting for PDU...
DEBUG:smpplib.client:<<00000010800000060000000000000002 (16 bytes)
DEBUG:smpplib.client:Read unbind_resp PDU
INFO:smpplib.client:Disconnecting...

**Comment by podshumok** [comment]
You should post a little more details on what you are doing or trying to do.

**Comment by eabumere** [comment]
Thanks Podshumok..

I want to send out sms using the ip, port, credentials given to me by my provider. I have followed religiously your code lines but I get the invalid destination error. is there something I am getting wrong? can you help with a sample format of the destination address? or rather just help resolve.

thanks.

**Comment by podshumok** [comment]
So if you delete `send_message` lines, then client connects, starts listening and disconnects without errors?

In this case, the problem seems to be in `dest_addr_ton` or `dest_addr_npi` params in `send_message` call. You need to set correct TON and NPI according to your destination number. You can figure out correct values from SMPP standard or your provider can help you with that.

**Comment by eabumere** [comment]
Thanks again podshumok. It is working now. It turned out to be from the providers. the python script worked just fine.
